Traceback (most recent call last):
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/patrickwalls/anaconda3/envs/jb/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.plot(np.cos(2*np.pi*d/365),residual,'.',alpha=0.1), plt.grid(True)
plt.xlabel('x1'), plt.ylabel('Residual')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m plt[38;5;241m.[39mplot(np[38;5;241m.[39mcos([38;5;241m2[39m[38;5;241m*[39mnp[38;5;241m.[39mpi[38;5;241m*[39md[38;5;241m/[39m[38;5;241m365[39m),[43mresidual[49m,[38;5;124m'[39m[38;5;124m.[39m[38;5;124m'[39m,alpha[38;5;241m=[39m[38;5;241m0.1[39m), plt[38;5;241m.[39mgrid([38;5;28;01mTrue[39;00m)
[1;32m      2[0m plt[38;5;241m.[39mxlabel([38;5;124m'[39m[38;5;124mx1[39m[38;5;124m'[39m), plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mResidual[39m[38;5;124m'[39m)
[1;32m      3[0m plt[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'residual' is not defined

